//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeficitNutricional
    {
        public int IdDeficit { get; set; }
        public int IdMinimo { get; set; }
        public int IdPatologia { get; set; }
    
        public virtual NutrienteMinimo NutrienteMinimo { get; set; }
        public virtual Patologia Patologia { get; set; }
    }
}
