//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBNutricion : DbContext
    {
        public DBNutricion()
            : base("name=DBNutricion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeficitNutricional> DeficitNutricional { get; set; }
        public virtual DbSet<ExcesoNutricional> ExcesoNutricional { get; set; }
        public virtual DbSet<Nutriente> Nutriente { get; set; }
        public virtual DbSet<NutrienteMaximo> NutrienteMaximo { get; set; }
        public virtual DbSet<NutrienteMinimo> NutrienteMinimo { get; set; }
        public virtual DbSet<Patologia> Patologia { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<TablaNutricional> TablaNutricional { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
    }
}
