//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrienteMaximo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NutrienteMaximo()
        {
            this.ExcesoNutricional = new HashSet<ExcesoNutricional>();
        }
    
        public int IdMaximo { get; set; }
        public int IdNutriente { get; set; }
        public decimal ValorMaximo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcesoNutricional> ExcesoNutricional { get; set; }
        public virtual Nutriente Nutriente { get; set; }
    }
}
