//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoArquitectura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaNutricional
    {
        public int IdTabla { get; set; }
        public int IdProducto { get; set; }
        public decimal Calorias { get; set; }
        public decimal GrasaTotal { get; set; }
        public decimal GrasasSaturadas { get; set; }
        public decimal GrasasTrans { get; set; }
        public decimal Colesterol { get; set; }
        public decimal Sodio { get; set; }
        public decimal CarbohidratosTotales { get; set; }
        public decimal FibraDietetica { get; set; }
        public decimal Azucares { get; set; }
        public decimal Proteina { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
